### ISSUE TITLE
חסר צד שרת

### ISSUE THREAD

**Issue by zspitz** [EdenDrori/client-side#1]
(ניתן להגיב להודעה זו).
אין לי צד שרת, מאד קשה לי לנסות להבין מה הולך.

**Comment by ElishevaSegal** [comment]
בוקר טוב!

קודם כל תודה רבה !

זה הלינק לתיקיית src של צד שרת.

  https://github.com/EdenDrori/Final_Project/tree/main/src

זה מספק או צריך ממש את כל הפרויקט?

שוב תודה!

‫בתאריך יום ד׳, 7 בפבר׳ 2024 ב-10:01 מאת ‪Zev Spitz‬‏ <‪
***@***.***‬‏>:‬

**Comment by zspitz** [comment]
זה בסדר גמור.

**Comment by ElishevaSegal** [comment]
מצוין,תודה!

‫בתאריך יום ד׳, 7 בפבר׳ 2024 ב-10:07 מאת ‪Zev Spitz‬‏ <‪
***@***.***‬‏>:‬
